export PATH := $(GOPATH)/bin:$(PATH)
export GO111MODULE=on
LDFLAGS := -s -w

# os-archs=darwin:amd64 darwin:arm64 freebsd:amd64 linux:amd64 linux:arm linux:arm64 windows:amd64 windows:arm64 linux:mips64 linux:mips64le linux:mips:softfloat linux:mipsle:softfloat linux:riscv64
os-archs=linux:amd64 windows:amd64

all: build

build: app

app:
	@$(foreach n, $(os-archs),\
		os=$(shell echo "$(n)" | cut -d : -f 1);\
		arch=$(shell echo "$(n)" | cut -d : -f 2);\
		gomips=$(shell echo "$(n)" | cut -d : -f 3);\
		target_suffix=$${os}_$${arch};\
		echo "Build $${os}-$${arch}...";\
		env CGO_ENABLED=0 GOOS=$${os} GOARCH=$${arch} GOMIPS=$${gomips} garble build -trimpath -ldflags "$(LDFLAGS)" -o ./release/monitoragentc_$${target_suffix} ./cmd/monitoragentc;\
		echo "Build $${os}-$${arch} done";\
	)
	@mv ./release/monitoragentc_windows_amd64 ./release/monitoragentc_windows_amd64.exe
	@# mv ./release/monitoragentc_windows_arm64 ./release/monitoragentc_windows_arm64.exe
